version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: my-rabbit
    volumes:
      - ./Blog.Infrastructure/RabbitMq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./Blog.Infrastructure/RabbitMq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
